{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edgeinstanceapi-chart.serviceAccountName" . }}
  labels:
    {{- include "edgeinstanceapi-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "edgeinstanceapi-chart.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "edgeinstanceapi-chart.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "edgeinstanceapi-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "edgeinstanceapi-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
