{{- if not .Values.global.oldServiceAssurance -}}
{{- if .Values.webhookTranslator.enabled -}}
#######################################################################################
# Copyright ETSI Contributors and Others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "osm.fullname" . }}-webhook-secret
  labels:
    {{- include "osm.labels" . | nindent 4 }}
data:
  # AIRFLOW_USER: {{ randAlphaNum 32 | b64enc | quote }}
  AIRFLOW_USER: {{ "admin" | b64enc | quote }}
  # AIRFLOW_PASS: {{ randAlphaNum 32 | b64enc | quote }}
  AIRFLOW_PASS: {{ "admin" | b64enc | quote }}
{{- end }}
{{- end }}