apiVersion: v1
kind: Service
metadata:
  name: {{ include "messagebroker-chart.fullname" . }}
  labels:
    {{- include "messagebroker-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: amqp
      port: {{ index .Values "service" "amqp-port" }}
      protocol: TCP
      targetPort: 5673
      {{- if index (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values "service" "amqp-nodePort") }}
      nodePort: {{ index .Values "service" "amqp-nodePort" }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: ui
      port: {{ index .Values "service" "ui-port" }}
      protocol: TCP
      targetPort: 8161
      {{- if index (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values "service" "ui-nodePort") }}
      nodePort: {{ index .Values "service" "ui-nodePort" }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: external
      port: {{ index .Values "service" "external-port" }}
      protocol: TCP
      targetPort: 61616
      {{- if index (and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values "service" "external-nodePort") }}
      nodePort: {{ index .Values "service" "external-nodePort" }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "messagebroker-chart.selectorLabels" . | nindent 4 }}
