#######################################################################################
# Copyright ETSI Contributors and Others.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#######################################################################################

apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: ${cluster_resource_name}-nodegroup
  annotations:
    crossplane.io/external-name: ${cluster_name}-nodegroup
  labels:
    provider: aws
    cluster: ${cluster_resource_name}
spec:
  forProvider:
    region: ${cluster_location}
    clusterNameSelector:
      matchLabels:
        provider: aws
        cluster: ${cluster_resource_name}
        type: cluster
    nodeRoleArnSelector:
      matchLabels:
        provider: aws
        cluster: ${cluster_resource_name}
        type: ec2
    subnetIdSelector:
        matchLabels:
          type: subnet
          access: private
    scalingConfig:
      - minSize: 1
        desiredSize: ${node_count}
        maxSize: 10
    diskSize: 30
    instanceTypes:
      - ${vm_size}
    tags:
      Name: ${cluster_name}
  # Use in case you wanted to use different credentials (i.e., ProviderConfig different than default)
  providerConfigRef:
    name: ${providerconfig_name}
