global:
  mecplatform:
    hostname: akkodismec.francecentral.cloudapp.azure.com
    borker:
      username: "5gmeta-platform"
      password: "5gmeta-platform"
      admin:
        username: "admin"
        password: "change"
  mariadb:
    rootpassword: &rootpassword  "changeme"
    username: "root"
    database: "instancedb"

mariadb-operator:
  fullnameOverride: "mariadb-operator"


mariadb-cluster:
  fullnameOverride: mariadb-cluster
  mariadb:
    galera:
      enabled: false
  replicas: 1
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  storage:
    size: 2Gi

apisix:
  fullnameOverride: "apisix"

  apisix:
    deployment:
      mode: "standalone"
      role: data_plane
      role_data_plane:
        config_provider: yaml
    admin:
      enabled: false

  control:
    enabled: false
  etcd:
    enabled: false
  service:
    type: NodePort
  ingress:
    enabled: true
    tls:
    - hosts:
      - akkodismec.francecentral.cloudapp.azure.com
      secretName: apisix-mecplatform-tls
    hosts: 
       - hosts: akkodismec.francecentral.cloudapp.azure.com
         paths:
           - "/"
    className: "nginx"
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 256k
      cert-manager.io/issuer: letsencrypt-prod

    extraVolumes:
      - name: routes
        configMap:
          name: apisix-routes
    extraVolumeMounts:
      - name: routes
        mountPath: /usr/local/apisix/conf/apisix.yaml
        subPath: apisix.yaml
