apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  apisix.yaml: |-
    routes:

      -
        uri: /api/v1/*
        upstream:
            nodes:
                    "edgeinstance-api.osm.svc.cluster.local:5000": 1
            type: roundrobin
        priority: 201

      -
        uri: /*
        upstream:
            nodes:
                    "ng-ui.osm.svc.cluster.local:80": 1
            type: roundrobin
        priority: 201

      -
        uri: /grafana/*
        upstream:
           nodes:
                  "grafana.osm.svc.cluster.local:80": 1
           type: roundrobin
           priority: 201
          

    #END
