apiVersion: v1
kind: ConfigMap
metadata:
  name: apisix-routes
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  apisix.yaml: |-
    routes:

      -
        uri: /api/v1/*
        upstream:
            nodes:
                    "edgeinstance-api.osm.svc.cluster.local:5000": 1
            type: roundrobin
        priority: 201
        plugins:
            openid-connect:
                access_token_in_authorization_header: false
                client_id: {{ .Values.global.oauth2.apisix.client }}
                client_secret: {{ .Values.global.oauth2.apisix.secret }}
                discovery: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/.well-known/openid-configuration
                introspection_endpoint: >-
                        https://{{  .Values.global.oauth2.issuer }}/realms/{{ .Values.global.oauth2.realm }}/protocol/openid-connect/token/introspect
                scope: "openid profile"
                bearer_only: false
                realm: {{ .Values.global.oauth2.realm }}
                introspection_endpoint_auth_method: client_secret_post
                redirect_uri: "/api/v1/redirect"
            cors:
                allow_origins: "*"
      -
        uri: /*
        upstream:
            nodes:
                    "ng-ui.osm.svc.cluster.local:80": 1
            type: roundrobin
        priority: 201

      -
        uri: /grafana/*
        upstream:
           nodes:
                  "grafana.osm.svc.cluster.local:80": 1
           type: roundrobin
           priority: 201
          

    #END
