# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      allowUiUpdates: true
      isDefault: true
      name: osm_prometheus
      type: prometheus
      url: http://prometheus:9090
    - access: proxy
      allowUiUpdates: true
      isDefault: false
      name: Prometheus
      type: prometheus
      url: http://osm-monitoring-kube-promet-prometheus.monitoring:9090
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = {{ .Values.global.mecplatform.hostname }}
    root_url = https://{{ .Values.global.mecplatform.hostname }}/grafana/
    serve_from_sub_path = true

  provider.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: Kubernetes Cluster
      name: Kubernetes Cluster
      options:
        path: /tmp/dashboards/Kubernetes Cluster
      orgId: 1
      type: file
    - disableDeletion: false
      folder: Open Source MANO
      name: Open Source MANO
      options:
        path: /tmp/dashboards/Open Source MANO
      orgId: 1
      type: file
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: osm
    meta.helm.sh/release-namespace: osm
  creationTimestamp: "2025-05-07T11:21:22Z"
  labels:
    app.kubernetes.io/instance: osm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.3.1
    helm.sh/chart: grafana-7.3.0
  name: grafana
  namespace: osm
  resourceVersion: "2101"
  uid: 9d08603d-5543-450d-b56a-971bdc2f53f8
