kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }} 
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: osm
apiVersion: v1
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      allowUiUpdates: true
      isDefault: true
      name: osm_prometheus
      type: prometheus
      url: http://prometheus:9090
    - access: proxy
      allowUiUpdates: true
      isDefault: false
      name: Prometheus
      type: prometheus
      url: http://osm-monitoring-kube-promet-prometheus.monitoring:9090
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = {{ .Values.global.mecplatform.hostname }}
    root_url = https://{{ .Values.global.mecplatform.hostname }}/grafana/
    serve_from_sub_path = true

  provider.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: Kubernetes Cluster
      name: Kubernetes Cluster
      options:
        path: /tmp/dashboards/Kubernetes Cluster
      orgId: 1
      type: file
    - disableDeletion: false
      folder: Open Source MANO
      name: Open Source MANO
      options:
        path: /tmp/dashboards/Open Source MANO
      orgId: 1
      type: file

