apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
stringData:
  root-password: {{ .Values.global.mariadb.rootpassword }}
  username: {{ .Values.global.mariadb.username }}
  database: {{ .Values.global.mariadb.database }}
